### ISSUE TITLE
how to set title?

### ISSUE THREAD

**Issue by YDJSZY** [elisherer/webpack-serve-waitpage#5]
hi! this is my code:
 app.use(webpackServeWaitpage(options, {
                title: 'admin'
            }));
but the waiting page is still "Development Server"

**Comment by elisherer** [comment]
@YDJSZY, can you share more information? The way you wrote it seems fine.

I tried the following as `serve.config.js`:
```js
const webpackServeWaitpage = require('webpack-serve-waitpage');

module.exports = {
  add: (app, middleware, options) => {
    app.use(webpackServeWaitpage(options, {
      title: 'admin'
    }));
  }
};
```
and the title changed..

**Comment by elisherer** [comment]
You didn't comment so I'm assuming this is resolved.

**Comment by YDJSZY** [comment]
![image](https://user-images.githubusercontent.com/14819143/43811543-93e4c1a6-9aef-11e8-8bca-5f3b3ec19ef1.png)
sorry! I want to the image "Development Server" change  to "admin"。but the title option is not to do that。has anything else api can do that ?

**Comment by elisherer** [comment]
As I said in the first comment, just create your own template.
