### ISSUE TITLE
jump to custom url when finish bundling?

### ISSUE THREAD

**Issue by ascoders** [elisherer/webpack-serve-waitpage#6]
It's useful to allow jump to custom url, if i want to debug code in a special `host`:

```typescript
app.use(webpackServeWaitpage(options, { url: 'https://www.google.com/' }))
```

Because we can't modify online html by webpack, so we can open localhost at first, and jump to special url after finsh bundling.

**Comment by elisherer** [comment]
Actually it is possible by creating a custom local ejs file and providing that url as a parameter to it.
I don't see it as a good feature since this page comes up only if the build hasn't finished yet. If it did then you will be left where you browsed to and not the url you provided.

**Comment by ascoders** [comment]
I think it's a good feature, it seems like "open a local page to see build progress, and jump to the real page after it has done."

If the waitpage is the same as the `open url` provided by `webpack-serve`, it will not work if the target url is a remote one.

**Comment by elisherer** [comment]
so you want to set the `open url` (in `webpack-serve`) to your localhost and change `webpack-serve-waitpage` to redirect to a different url?

**Comment by ascoders** [comment]
@elisherer Yes, and `webpack-serve-waitpage` just need receive `redirect` param to allow a custom jump. The default is false, which does not have an impact on the existing design.

**Comment by elisherer** [comment]
I think in the way it is handled today (meta refresh), it's very difficult to accomplish what you want. Do you want to try to create a PR?

**Comment by elisherer** [comment]
As I said, it is not possible to implement this feature using the current design, If you can think of a way to implement it, you are welcome to create a PR, Closed.
